# Generated by Django 6.0 on 2025-12-17 06:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternetProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Provayder nomi')),
                ('location', models.CharField(max_length=200, verbose_name='Joylashuv')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Manzil')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Internet Provayder',
                'verbose_name_plural': 'Internet Provayderlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NetworkIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200, verbose_name='Xizmat nomi')),
                ('issue_type', models.CharField(choices=[('outage', "To'liq ishlamayapti"), ('slow', 'Sekin ishlayapti'), ('intermittent', 'Vaqti-vaqti bilan')], max_length=100, verbose_name='Muammo turi')),
                ('severity', models.CharField(choices=[('low', 'Past'), ('medium', "O'rtacha"), ('high', 'Yuqori')], default='medium', max_length=50)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tarmoq Muammosi',
                'verbose_name_plural': 'Tarmoq Muammolari',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='SpeedTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_speed', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Yuklab olish tezligi (Mbps)')),
                ('upload_speed', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Yuklash tezligi (Mbps)')),
                ('ping', models.IntegerField(verbose_name='Ping (ms)')),
                ('jitter', models.IntegerField(blank=True, null=True, verbose_name='Jitter')),
                ('packet_loss', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name="Paket yo'qolishi (%)")),
                ('connection_type', models.CharField(choices=[('multi', 'Multi'), ('single', 'Single')], default='multi', max_length=50)),
                ('test_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Test sanasi')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='speedtest.internetprovider')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Speed Test Natijasi',
                'verbose_name_plural': 'Speed Test Natijalari',
                'ordering': ['-test_date'],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='Baho (0-10)')),
                ('comment', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='speedtest.speedtestresult')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi Fikri',
                'verbose_name_plural': 'Foydalanuvchi Fikrlari',
            },
        ),
    ]
